package com.cokelord.skyblocksimplified.feature;

import com.cokelord.skyblocksimplified.keybind.KeyCombo;

import java.util.List;
import java.util.function.BooleanSupplier;
import java.util.function.Consumer;
import java.util.function.IntConsumer;
import java.util.function.IntSupplier;
import java.util.function.Supplier;

/**
 * Declarative settings rows. A feature that returns a non-empty {@link Feature#getSettingRows()} gets its
 * settings panel (cog, panel height and drawing) generated by MainScreen from this list, instead of a
 * hand-written {@code drawXContent}/{@code expandedContentHeight} pair. Every row can be hidden with
 * {@code visible} (re-evaluated each frame), and every setter is expected to persist on its own terms —
 * MainScreen calls {@code ConfigManager.save()} after each change.
 */
public sealed interface SettingRow {
	BooleanSupplier ALWAYS = () -> true;

	BooleanSupplier visible();

	record Toggle(String label, BooleanSupplier get, Consumer<Boolean> set, String tooltip, BooleanSupplier visible) implements SettingRow {
		public Toggle(String label, BooleanSupplier get, Consumer<Boolean> set, String tooltip) {
			this(label, get, set, tooltip, ALWAYS);
		}
	}

	/** Integer slider from {@code min} to {@code max}; {@code suffix} is appended to the shown value. */
	record Slider(String label, int min, int max, IntSupplier get, IntConsumer set, String suffix, String tooltip, BooleanSupplier visible) implements SettingRow {
		public Slider(String label, int min, int max, IntSupplier get, IntConsumer set, String suffix, String tooltip) {
			this(label, min, max, get, set, suffix, tooltip, ALWAYS);
		}
	}

	/** Click-to-cycle value box. */
	record Cycle(String label, Supplier<String> value, Runnable next, String tooltip, BooleanSupplier visible) implements SettingRow {
		public Cycle(String label, Supplier<String> value, Runnable next, String tooltip) {
			this(label, value, next, tooltip, ALWAYS);
		}
	}

	/** Full color picker (square + RGB sliders + hex field). {@code key} must be unique across the menu. */
	record Color(String label, String key, IntSupplier get, IntConsumer set, int defaultColor, BooleanSupplier visible) implements SettingRow {
		public Color(String label, String key, IntSupplier get, IntConsumer set, int defaultColor) {
			this(label, key, get, set, defaultColor, ALWAYS);
		}
	}

	/** Labeled single-line text field. {@code id} must be unique across the menu. */
	record Text(String label, String id, Supplier<String> get, Consumer<String> set, String placeholder, BooleanSupplier visible) implements SettingRow {
		public Text(String label, String id, Supplier<String> get, Consumer<String> set, String placeholder) {
			this(label, id, get, set, placeholder, ALWAYS);
		}
	}

	record Keybind(String label, KeyCombo combo, BooleanSupplier visible) implements SettingRow {
		public Keybind(String label, KeyCombo combo) {
			this(label, combo, ALWAYS);
		}
	}

	record Button(String label, Runnable action, BooleanSupplier visible) implements SettingRow {
		public Button(String label, Runnable action) {
			this(label, action, ALWAYS);
		}
	}

	/** The mod's shared sound picker block (built-in cycle + preview, custom file import, volume/pitch). */
	record Sound(com.cokelord.skyblocksimplified.sound.CustomSoundOption sound, BooleanSupplier visible) implements SettingRow {
		public Sound(com.cokelord.skyblocksimplified.sound.CustomSoundOption sound) {
			this(sound, ALWAYS);
		}
	}

	/** Wrapped gray note text (disclaimers, requirements). */
	record Note(String text, BooleanSupplier visible) implements SettingRow {
		public Note(String text) {
			this(text, ALWAYS);
		}
	}

	/** Collapsible dropdown group: a header row that expands to show {@code children}. Collapsed by default. */
	record Group(String label, String key, List<SettingRow> children, BooleanSupplier visible) implements SettingRow {
		public Group(String label, String key, List<SettingRow> children) {
			this(label, key, children, ALWAYS);
		}
	}
}
